[package]
name = "axalloc"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS global memory allocator"
license.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axalloc"

[features]
default = []
level-1 = []
tracking = ["dep:percpu", "dep:axbacktrace"]

[dependencies]
buddy-slab-allocator = { path = "../../allocator" , features = ["log", "tracking"]}
axbacktrace = { workspace = true, optional = true }
axerrno.workspace = true
cfg-if.workspace = true
kspin.workspace = true
log.workspace = true
memory_addr.workspace = true
percpu = { workspace = true, optional = true }
strum = { version = "0.27.2", default-features = false, features = ["derive"] }
